services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "5500:5500"
    volumes:
      - data:/data

volumes:
  data:
